### ISSUE TITLE
Check for Conformity to Project Specification.

### ISSUE THREAD

**Issue by ghost** [ElijahTheRandom/JavaProject321#14]
The finished build needs to fit the project specification.

Work to do would be to review the requirements posted by Dr. R and then making sure the project conforms. Any issues can be raised in this thread.

**Comment by oliviaallen27** [comment]
Project requirements: 
1.	Graphical user interface
a.	The underlying software engineering principle will be the model-view-control  pattern. There is a lot to do here; you will need to think through the user interactions. User stories, use cases, and CRC cards will help.
2.	Text display or processing, could be both (html or other)
3.	Graphics sampled or constructive with manipulation or animation, could be all four.
a.	Sampled graphics are images that are like those taken by a camera.
b.	Constructed graphics are images built from primitive graphic shapes.
c.	Manipulating graphics is changing them in some way (colors, size, contrast and so on)
d.	Animation is graphics manipulation over time.
4.	Storage and retrieval of information (flat file,database, XML, or other).
*The project must clearly demonstrate the ideas of the Model-View-Control pattern/paradigm.
